spring.application.name=SchoolBoard
spring.datasource.url=jdbc:postgresql://localhost:5432/school_board
spring.datasource.username=postgres
spring.datasource.password=Kw62590889

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration-ms=86400000
